// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdaoubpm296VMMKLf3q8mt5mneJhynfEM',
    appId: '1:328485606986:web:512b703c86c9104b8178b3',
    messagingSenderId: '328485606986',
    projectId: 'alphacodecourses',
    authDomain: 'alphacodecourses.firebaseapp.com',
    storageBucket: 'alphacodecourses.appspot.com',
    measurementId: 'G-WT5EW5B42H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCouslZRJKKHeMkViIk7Mg-1HNeLQfv8Cg',
    appId: '1:328485606986:android:d81e659a52ca7e278178b3',
    messagingSenderId: '328485606986',
    projectId: 'alphacodecourses',
    storageBucket: 'alphacodecourses.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0ulsVheBK12-9OQeGTZEuU3ruR_56m6A',
    appId: '1:328485606986:ios:7cff550bd69478798178b3',
    messagingSenderId: '328485606986',
    projectId: 'alphacodecourses',
    storageBucket: 'alphacodecourses.appspot.com',
    iosClientId: '328485606986-ji7e6rth3lqdbttpet7dbeum7ejjv4f5.apps.googleusercontent.com',
    iosBundleId: 'com.attendance.ibrahim.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0ulsVheBK12-9OQeGTZEuU3ruR_56m6A',
    appId: '1:328485606986:ios:7da355761c6767a98178b3',
    messagingSenderId: '328485606986',
    projectId: 'alphacodecourses',
    storageBucket: 'alphacodecourses.appspot.com',
    iosClientId: '328485606986-1aqv9mki8nlgrcnqsa27p8pbt45t9uec.apps.googleusercontent.com',
    iosBundleId: 'com.attendance.ibrahim.attendanceApp.RunnerTests',
  );
}
